#!/bin/bash

URL="https://pokeapi.co/api/v2/pokemon/"

OUTPUT_FILE="data.json"

response=$(curl -s -w"%{http_code}" -o $OUTPUT_FILE "$URL")
# Save the response to a file and capture the HTTP status code
http_status="${response: -3}"

if [ "$http_status" -eq 200 ]; then
    echo "Request was succesful. Data saved to $OUTPUT_FILE"
else
    # log error with timestamp to errors.txt
    echo "[$(date)] ERROR: Failed to retrieve data. Http Status code ${http_status}" >> errors.txt

    rm -f data.json
fi
