#!/bin/bash
pokemon_list=("pikachu" "bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

mkdir -p pokemon_data
# Loop throgh each pokemn
for pokemon in "${pokemon_list[@]}"; do

    URL="https://pokeapi.co/api/v2/pokemon/$pokemon/"

    OUTPUT_FILE="${pokemon}.json"

    attempts=0
    max_attempts=3
    success=false

    # Retry logic
    while [ "$attempts" -lt "$max_attempts" ]; do
        ((attempts++))

        # Make API call
        response=$(curl -s -w "%{http_code}" -o "$OUTPUT_FILE" "$URL")
        # Save the response to a file and capture the HTTP status code
        http_status="${response: -3}"

        echo "Attempt $attempts: Fetching data for ${pokemon}..."
        if [ "$http_status" -eq 200 ]; then
            
            mv -f "$OUTPUT_FILE" "pokemon_data/"
            echo "Success: Saved data to pokemon_data/$OUTPUT_FILE"
            success=true
            break
        else
            echo "Attempt $attempts failed  for $pokemon (HTTP $http_status)"
            sleep 1 # Wait before retrying
        
        fi
    done
    if [ "$success" = false ]; then
        echo "[$(date)] Error: Failed to retrieve data for $pokemon after $max_attempts attempts. HTTP status code $http_status" >> errors.txt
        rm -f "$OUTPUT_FILE"
    fi
done
