#!/bin/bash
pokemon_list=("pikachu" "bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

# Loop throgh each pokemn
for pokemon in "${pokemon_list[@]}"; do

    URL="https://pokeapi.co/api/v2/pokemon/$pokemon/"

    OUTPUT_FILE="${pokemon}.json"

    response=$(curl -s -w"%{http_code}" -o $OUTPUT_FILE "$URL")
    # Save the response to a file and capture the HTTP status code
    http_status="${response: -3}"

    echo "Fetching data for ${pokemon}..."

    if [ "$http_status" -eq 200 ]; then
        # save to pokemon file inside pokemon_data directory
        mkdir -p pokemon_data
        mv -f $OUTPUT_FILE pokemon_data/
        echo "Saved data to pokemon_data/$OUTPUT_FILE"
    else
        # log error with timestamp to errors.txt
        echo "[$(date)] ERROR: Failed to retrieve data for $pokemon. Http Status code ${http_status}" >> errors.txt

        rm -f data.json
    fi
done